### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by RuijieYu** [doums/bato#1]
It would be great if you add the license directly into the repository rather than only putting it in the read me. (That way GitHub should also auto-detect it if that is relevant).

**Comment by doums** [comment]
As you can read in the [FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/), to apply the MPL 2.0 to my code, it doesn't require any kind of license file. Instead I must add to each source file the license header notice. It's what I did. This is how the MPL 2.0 works. Make no sense to put something in a license file related to MPL 2.0 because all my source code files contain the header license notice.
